# permissions for end users to view nameservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nameservice-viewer-role
rules:
- apiGroups:
  - rocketmq.apache.org
  resources:
  - nameservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rocketmq.apache.org
  resources:
  - nameservices/status
  verbs:
  - get
