# permissions for end users to edit nameservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nameservice-editor-role
rules:
- apiGroups:
  - rocketmq.apache.org
  resources:
  - nameservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rocketmq.apache.org
  resources:
  - nameservices/status
  verbs:
  - get
