# permissions for end users to view topictransfers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topictransfer-viewer-role
rules:
- apiGroups:
  - rocketmq.apache.org
  resources:
  - topictransfers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rocketmq.apache.org
  resources:
  - topictransfers/status
  verbs:
  - get
